### ISSUE TITLE
config dir only using prospectors from first yml file

### ISSUE THREAD

**Issue by nigelp-vci** [elastic/filebeat#344] opened 2016-03-08 13:40 UTC
filebeat on windows, using the config_dir correctly loads/fetchs all the additional yml files in the directory.
however only prospectors from the first yml file are actually started

**Comment by ruflin** [comment] 2016-03-08 14:39
Can you share the content of your config files to make sure the configuration files are correct?

**Comment by nigelp-vci** [comment] 2016-03-08 15:05
after further testing i've found the following:

Scenario 1: filebeat.yml contains all prospectors. All files logged.
Scenario 2: filebeat.yml contains no prospectors, config_dir contains 2 yml config files: iis, api. Only iis logged
Scenario 3: filebeat.yml contains api prospectors, config_dir contains iis yml config. all fileslogged.
Scenario 4: filebeat.yml contains no prospectors, config_dir contains 1 yml config with 2 prospectors (iis, api). all files logged.

This indicates an problem with config for the api log files, yet these are processed when in the filebeat.yml or the iis.yml

- filebeat.yml - no prospectors:
`
############################# Filebeat ######################################
filebeat:
  prospectors:

  registry_file: "C:/ProgramData/filebeat/registry"
  config_dir: C:\Program Files\filebeat\configs
 
############################# Output ##########################################
output:

  ### Logstash output
  logstash:
    hosts: ["servername:port"]

############################# Shipper #########################################

shipper:
  #tags: ["service-X", "web-tier"]

############################# Logging #########################################

logging:

  #to_syslog: false
  to_files: false
`

- iis.yml - iis prospectors
`
############################# Filebeat ######################################
filebeat:
  prospectors:
    ### IIS logs
    -
      paths:
        - E:\logs\inetpub\LogFiles\*\*.log
      input_type: log
      document_type: iis_log

      ## exclude_lines. By default, no lines are dropped.  (RegEx)
      exclude_lines: ["^#"]

      scan_frequency: 10s
      force_close_files: true
## Remaing entries are required but ignored::	  
############################# Output ##########################################
output:
############################# Shipper #########################################
shipper:
############################# Logging #########################################
logging:
`
- api.yml - api prospectors
`
############################# Filebeat ######################################
filebeat:
  prospectors:
    ### Api logs
    -
      paths:
        - E:\logs\\api\*.log
      input_type: log
      document_type: api_log

      ## exclude debug and trace lines - filebeat fails RegEx :( << implement on logstash instead
      ##exclude_lines: ["^[\\d-:\\.]* [\\d-:\\.]* (DEBUG|TRACE)"]
      
      exclude_files: ["error"]

      fields:
        source: api
      fields_under_root: false

      scan_frequency: 10s
      force_close_files: true
## Remaing entries are required but ignored::	  
############################# Output ##########################################
output:
############################# Shipper #########################################
shipper:
############################# Logging #########################################
logging:
`

**Comment by nigelp-vci** [comment] 2016-03-08 15:06
seems the "write" is reformating the config file entries above

**Comment by ruflin** [comment] 2016-03-08 15:08
@nigelp-vci Use 3 backticks around the config files for better formatting.

**Comment by nigelp-vci** [comment] 2016-03-08 15:10
- filebeat.yml - no prospectors

```
############################# Filebeat ######################################
filebeat:
  prospectors:

  registry_file: "C:/ProgramData/filebeat/registry"
  config_dir: C:\Program Files\filebeat\configs

############################# Output ##########################################
output:

  ### Logstash output
  logstash:
    hosts: ["server:port"]


############################# Shipper #########################################
shipper:

############################# Logging #########################################
logging:
  to_files: false
```

**Comment by nigelp-vci** [comment] 2016-03-08 15:11
- iis.yml 
```
############################# Filebeat ######################################
filebeat:
  prospectors:
    ### IIS logs
    -
      paths:
        - E:\logs\inetpub\LogFiles\*\*.log

		input_type: log
      document_type: iis_log

      exclude_lines: ["^#"]

      scan_frequency: 10s
      force_close_files: true
### Remaing entries are required but ignored::	  
############################# Output ##########################################
# Multiple outputs may be used.
output:
############################# Shipper #########################################
shipper:
############################# Logging #########################################
logging:
```

**Comment by nigelp-vci** [comment] 2016-03-08 15:12
- api.yml
```
############################# Filebeat ######################################
filebeat:
  prospectors:   
    ### Api logs: 
    -
      paths:
        - E:\logs\api\*.log
        
      input_type: log
      document_type: api_log

      # exclude debug and trace lines <<< filebeat RegEx Fails! << implent @ logstash instead
      #exclude_lines: ["^[\\d-:\\.]* [\\d-:\\.]* (DEBUG|TRACE)"]
      
      exclude_files: ["error"]

      fields:
        source: api
      fields_under_root: false

      scan_frequency: 10s
      force_close_files: true
	  
### Remaing entries are required but ignored::	  
############################# Output ##########################################
output:
############################# Shipper #########################################
shipper:
############################# Logging #########################################
logging:
```

**Comment by nigelp-vci** [comment] 2016-03-08 15:14
from testing it would seem that there is a problem with the api.yml file
yet including the prospector from that file into either the iis.yml or the filebeat.yml works

**Comment by ruflin** [comment] 2016-03-08 15:18
That is definitively strange. One unrelated part that surprises me is that the remaining entries are required. They shouldn't. Which filebeat version are you using? What error do you get if you remove it?

BTW: Github comments can be edited, so next time you don't have to repost it.

**Comment by nigelp-vci** [comment] 2016-03-08 15:21
filebeat 1.1.1 for windows

extract from including yml file:
```
  # Full Path to directory with additional prospector configuration files. Each file must end with .yml
  # These config files must have the full filebeat config part inside, but only
  # the prospector part is processed. All global options like spool_size are ignored.
  # The config_dir MUST point to a different directory then where the main filebeat config file is in.
  #config_dir:
```

**Comment by ruflin** [comment] 2016-03-08 15:26
I see, you are "interpreting" the "full filebeat config part" as output, shipper and logging. These three are actually configurations from libbeat and not filebeat. The reason that is is written that way is because some people left out filebeat on the top level and only put prospectors in. Probably we should mention specifically that output, shipper and logging is not needed. (@dede What do you think?).

Can you try again without the bottom part? It should make any difference, but it is worth a try as I currently can't see the problem in api.yml.

Can you start filebeat with the `-e -d "*"` flags and post the output here? Have all config files the same access rights?

**Comment by nigelp-vci** [comment] 2016-03-08 15:43
Amazingly that solved it ! (removing the additional entries in the additional config files, so that they each only had "Prospector")

**Comment by nigelp-vci** [comment] 2016-03-08 15:43
thanks for your help

**Comment by nigelp-vci** [comment] 2016-03-08 15:44
any chance you can see why the exclude_lines RegEx fails

**Comment by ruflin** [comment] 2016-03-08 15:48
That is really strange to be honest. Glad it was resolved by removing it but I will dig here deeper on if that is an issue if there are "too many" config options in.

In the future please use https://discuss.elastic.co/c/beats/filebeat first as we try to keep only confirmed bugs in Github. For the regexp, please open a new topic on discuss and also post an example of your log file.

**Closed by ruflin** 2016-03-08 15:48 UTC

**Comment by nigelp-vci** [comment] 2016-03-08 15:53
No worries. Ended up @ Github after googling “filebeat bug” top few results all at github

Perhaps a change request to “ignore” anything other than filebeat entries in the files from the config directory ?

Nigel Piggott  |  Vantage Computing Ltd

t +44 (0)1462 791120  |  f +44 (0)1462 888480

**Comment by ruflin** [comment] 2016-03-08 15:54
We will have better config validation in the future with ucfg: https://github.com/urso/ucfg. This will solve it indirectly.
