### ISSUE TITLE
Not sending to logstash on CentOS 7

### ISSUE THREAD

**Issue by ivrh** [elastic/filebeat#317] opened 2015-12-23 09:11 UTC
We have a number of services running CentOS 7.
Filebeat installed via yum repository.
Configuration file is set to send logs data to ELK server (logstash) via FQDN and TLS.

When restarting filebeat, it sends a small portion of log data to the logstash server for about a second, so it works. However no more data is coming through. Restarting the filebeat daemon again sends about 1 second of log data, then it stops. 

There is no log records to indicate any problems.

I have removed the init script and replaced it with this filebeat.service file
<code>
[Unit]
Description=Filebeat Service
Wants=network-online.target
After=syslog.target network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/filebeat -c /etc/filebeat/filebeat.yml
Restart=always

[Install]
WantedBy=multi-user.target
</code>

Now it runs via systems, but nothing changed.

Any ideas on the further steps to fix this?

**Comment by lewis151** [comment] 2015-12-24 16:37
I have a similar problem running on Ubuntu 14.04, the old logstash-forwarder works fine on another Ubuntu 14.04 system, but it has less log data information.  The only time filebeat will send log data is when the filebeat service is restarted.  The filebeat log data is not sent after Ubuntu 14.04 is rebooted.  I have several Ubuntu VMs running on XenServer 6.5. 
I don't know what information needs to be attached.

**Comment by ruflin** [comment] 2015-12-27 08:33
@ivrh @lewis151 Does it work when you run filebeat manually? Can you run it with the option `-e -d "*"` and post the debugging output?

**Comment by ivrh** [comment] 2015-12-28 00:06
@ruflin When I run filebeat manually in the foreground, I saw error messages about inability to connect to local elasticsearch. This was strange, as filebeat output was set `enabled: false` in accordance with the installation guide https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-centos-7
So I did comment out both: elasticsearch and host lines, leaving logstash is the only output option in filebeat.yml file. This seem to fix the problem.

Either enabled option was removed recently or the guide I was referring to is incorrect.

Thanks for your help.

**Comment by ruflin** [comment] 2015-12-28 08:45
@ivrh The enabled option was removed before release 1.0.0. I just send a message to them so they can adjust it. Does this mean the problem is resolved? @lewis151 ?

**Comment by ivrh** [comment] 2015-12-28 23:51
@ruflin Yes, the problem is resolved for me in all CenOS 7 servers, where CentOS 6 was running okay with the `enabled: false` option. However I have removed it and followed the same steps on commenting out output options for elasticsearch.
All logs are now coming to the centralised logstash server just fine.
Thank you for your help.

**Comment by ruflin** [comment] 2015-12-29 12:39
@ivrh Could it be that on CentOS 6 you were running an older version?

**Comment by lewis151** [comment] 2015-12-29 14:20
elasticsearch was set enabled: false in accordance with the installation guide. I commented it out.   elasticsearch was the only place which had a enabled: false entry.  I am receiving sporadic data to kibana.   The first change I noticed was log data was received after boot. The received data arrives as follows:


Count 3,074 at 08:00:00

Count 1,028 at 08:30:00

Count       97 at 12:00:00

Count     528 at 12:30:00

Count     566 at 13:00:00

Count     468 at  22:00:00


I am running Ubuntu 14.04 fully updated.  I am still trying to learn how ELK works. Oh there are three more Ubuntu 14.04 system in my playground.  Nothing going on with them except testing ELK & Zabbix.


More news as it develops.
<https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-centos-7>

[https://community-cdn-digitalocean-com.global.ssl.fastly.net/assets/tutorials/images/large/elk---twitter.png?1428343951]<https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-centos-7>

How To Install Elasticsearch, Logstash, and Kibana (ELK ...<https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-centos-7>
www.digitalocean.com
In this tutorial, we will go over the installation of the Elasticsearch ELK Stack on CentOS 7-that is, Elasticsearch 2.1.0, Logstash 2.1.0, and Kibana 4.3.0. We ...


So I did comment out both: elasticsearch and host lines, leaving logstash is the only output option in filebeat.yml file. This seem to fix the problem.


Lewis Litchfield
Technology Services - Viking Center Lab
University of South Florida Sarasota-Manatee
941-359-4231


________________________________

**Comment by lewis151** [comment] 2015-12-29 17:55
I am lost.  /var/lib/filebeat/registery has {}    ie blank

I have from the auth.log file  -but nothing is sent to the ELK server.  Wireshark & ELK recognize the log file being sent after a service filebeat restart has been executed.  If any other data/updates is sent , it is sporadic.  My Ubuntu 14-04 machine running logstash-forwarder will imediately send the log data as soon as I ihave completed the failed logon session.

How can Idetermine what is going wrong with filebeat?



^Cxen31ubut14dt@xen31ubut14dt-0:~tail -20 /var/log/auth.log
Dec 29 12:40:04 xen31ubut14dt-0 sshd[14562]: Failed password for invalid user wireshark from 131.247.31.27 port 61812 ssh2
Dec 29 12:40:05 xen31ubut14dt-0 sshd[14562]: pam_unix(sshd:auth): check pass; user unknown
Dec 29 12:40:07 xen31ubut14dt-0 sshd[14562]: Failed password for invalid user wireshark from 131.247.31.27 port 61812 ssh2
Dec 29 12:40:08 xen31ubut14dt-0 sshd[14562]: pam_unix(sshd:auth): check pass; user unknown
Dec 29 12:40:11 xen31ubut14dt-0 sshd[14562]: Failed password for invalid user wireshark from 131.247.31.27 port 61812 ssh2
Dec 29 12:40:12 xen31ubut14dt-0 sshd[14562]: pam_unix(sshd:auth): check pass; user unknown
Dec 29 12:40:14 xen31ubut14dt-0 sshd[14562]: Failed password for invalid user wireshark from 131.247.31.27 port 61812 ssh2
Dec 29 12:40:15 xen31ubut14dt-0 sshd[14562]: pam_unix(sshd:auth): check pass; user unknown
Dec 29 12:40:17 xen31ubut14dt-0 sshd[14562]: Failed password for invalid user wireshark from 131.247.31.27 port 61812 ssh2
Dec 29 12:40:19 xen31ubut14dt-0 sshd[14562]: pam_unix(sshd:auth): check pass; user unknown
Dec 29 12:40:21 xen31ubut14dt-0 sshd[14562]: Failed password for invalid user wireshark from 131.247.31.27 port 61812 ssh2
Dec 29 12:40:21 xen31ubut14dt-0 sshd[14562]: Disconnecting: Too many authentication failures for wireshark [preauth]
Dec 29 12:40:21 xen31ubut14dt-0 sshd[14562]: PAM 5 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=131.247.31.27
Dec 29 12:40:21 xen31ubut14dt-0 sshd[14562]: PAM service(sshd) ignoring max retries; 6 > 3
Dec 29 12:41:00 xen31ubut14dt-0 sshd[14629]: Accepted password for xen31ubut14dt from 131.247.31.27 port 61819 ssh2
Dec 29 12:41:00 xen31ubut14dt-0 sshd[14629]: pam_unix(sshd:session): session opened for user xen31ubut14dt by (uid=0)
Dec 29 12:41:00 xen31ubut14dt-0 systemd-logind[528]: New session 9 of user xen31ubut14dt.
Dec 29 12:44:40 xen31ubut14dt-0 sudo: xen31ubut14dt : TTY=pts/1 ; PWD=/home/xen31ubut14dt ; USER=root ; COMMAND=/usr/sbin/service filebeat status
Dec 29 12:44:40 xen31ubut14dt-0 sudo: pam_unix(sudo:session): session opened for user root by xen31ubut14dt(uid=0)
Dec 29 12:44:40 xen31ubut14dt-0 sudo: pam_unix(sudo:session): session closed for user root
xen31ubut14dt@xen31ubut14dt-0:~$



Lewis Litchfield
Technology Services - Viking Center Lab
University of South Florida Sarasota-Manatee
941-359-4231


________________________________

**Comment by ruflin** [comment] 2015-12-30 14:40
@lewis151 The best way to "debug" filebeat is using the debug option `-e -d "*"`

Can we please move the discussion to https://discuss.elastic.co/c/beats/filebeat as we want to keep the github issues for confirmed bugs and feature request? Closing this one but will of course continue answering on discuss.

**Closed by ruflin** 2015-12-30 14:40 UTC

**Comment by jarodsolano** [comment] 2016-01-08 23:11
I wanted to point out that I ran into the same issue on Centos 6.5.  I removed all 'enabled: false' strings except for logstash, and now data is showing.  I am now looking through data to verify.

**Comment by lewis151** [comment] 2016-01-09 15:09
It doesn't work with Windows 7 either!!


Lewis Litchfield
Technology Services - Viking Center Lab
University of South Florida Sarasota-Manatee
941-359-4231


________________________________

**Comment by ruflin** [comment] 2016-01-10 19:20
@lewis151 In case the above posts didn't help, please open a topic on https://discuss.elastic.co/c/beats/filebeat and report the fields listed here: https://discuss.elastic.co/t/beats-how-to-report-an-issue/38301
