### ISSUE TITLE
Fix issue when adding fields per prospector

### ISSUE THREAD

**Issue by vmcano** [elastic/filebeat#137] opened 2015-10-26 16:22 UTC
I am using the following configuration to send logs to Logstash with Filebeat:

````
        -
      paths:
        - /logs/test.log
      fields:
        type: test
````
As you can see, I am trying to add more information like type but the field that Logstash receives is "field.type". I guess this is a malfunctioning and it should be simply "type".

**Comment by ruflin** [comment] 2015-10-26 16:46
@vmcano As we are sending JSON to logstash, it should actually retrieve the following: 
`"fields":{"type":"test"}` I briefly tried it on my machine with the following settings:

```
filebeat:
  # List of prospectors to fetch data
  prospectors:
    -
      # Paths that should be crawled and fetched
      paths:
        - /var/log/*.log
      fields:
        hello: world
        name: ruflin
```

Inside elasticsearch I got the following output after it was sent through logstash:
```
"fields":{"hello":"world","name":"ruflin"}
```

What is the logstash configuration you are using? Which plugin are you using?

**Comment by vmcano** [comment] 2015-10-26 17:10
When I said I get "field.type" I meant the field "type" was inside the field "fields". So, the result that both of us get is the same. Sorry for not explaining it well.

However, if I set the previous configuration, I expect the field "type" to be modified, and not a new field inside a field called "fields". So what I expect from your example would be:
````
"hello":"world",
"name":"ruflin",
````

Wouldn't it make more sense to modify existing fields or to create first level fields instead of grouping all of them under a field called "fields"?

**Comment by ruflin** [comment] 2015-10-26 17:24
If we don't group the fields under `fields` we have the risk of conflicting with other data entries. Already in your case would be a conflict, as the field `type` is already in use.

Is using "subfields" preventing you from doing some queries or things you were doing before?

**Comment by vmcano** [comment] 2015-10-26 19:09
This functioning is a little different from the functioning of Logstash-Forwarder, but in my case I only have to change the configuration of some Logstash filters. However, this could lead to bigger changes for other people.
Regarding to queries, I didn't have any problem.

**Comment by ruflin** [comment] 2015-10-26 20:49
@vmcano Good to know. It means we should mention this in the migration guide from logstash-forwarder. https://github.com/elastic/filebeat/issues/138

What other potential bigger changes were you thinking of?

**Comment by vmcano** [comment] 2015-10-27 08:52
@ruflin I didn't have to do many changes. Migration from Logstash-Forwarder to Filebeat was quite smooth.
A thing that I missed was a more comprehensive log in Filebeat, because even with the `logging` option in the configuration file, there is too little information.

**Comment by ruflin** [comment] 2015-10-27 08:59
Any specific log outputs you were missing / looking for?

**Comment by vmcano** [comment] 2015-10-27 09:27
Logs produced by Logstash-Forwarder are really helpful as they give you the opportunity to check if connection is correctly established, if file is being harvested and at what point... I'd like to have this information in Filebeat because looking for errors is difficult without it.

At the moment, the `logging` part of my config file looks like this:
````
logging:
  # Enable file rotation with default configuration
  to_files: true

  # Do not log to syslog
  to_syslog: false

  files:
    path: /var/log/filebeat
    name: filebeat.log
    keepfiles: 10
````
And after 20 hours working, I have no information at all.

**Comment by ruflin** [comment] 2015-10-27 15:54
@vmcano The default behaviour of filebeat is to only write "Errors" to the log. So the good news is that it seems there weren't any errors in the last 20 hours. The bad news is that this is probably not what you expected. You can use the -v option to also log info and warn log messages. Unfortunately at the moment there is no more fine grained option to set the log level. But based on the discussions we just had we added it to our to do list.

Can you check if the log files are created as expected with the -v option?

**Comment by vmcano** [comment] 2015-10-28 16:01
@ruflin With the `-v` option I get more information, but less than I'd like.
I've found that some information like the number of log lines sent can be obtained using the `-d publish` option. However, this option offers too much information.

**Comment by tsg** [comment] 2015-10-28 16:29
@vmcano I think `-d prospector` would give you a pretty similar output to what LSF has.

**Comment by ruflin** [comment] 2015-10-29 07:36
@vmcano With https://github.com/elastic/libbeat/pull/223 with also introduced log levels which should also help here.

**Comment by congpine** [comment] 2015-11-17 12:13
I'm having similar issue checking the fields that inserted by filebeat.
I'm setting this up for new system, don't use logstash-forwarder. I'm trying to recognise the logs that filebeat sending over to logstash-indexer ( in this case, it is apache logs)
My filebeat.yml:
```      
      type: log
      fields:
          logs_type: apache
```
JSON sent to logstash-indexer:
```
"fields": {
    "logs_type": "apache"
  },
  "fileinfo": {},
  "input_type": "",
```

However, my filter doesn't seem to get the correct fields.logs_type value
```
if [fields.logs_type] == "apache" {
      grok {
       patterns_dir => "/etc/logstash/conf.d/grok_pattern/apache"
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
  }
```

If my above method is wrong, then what would be the best way to get the logs type and apply correct filter in Logstash-indexer?
I'm not quite sure what is the different between:
document_type, type (only support: log or stdin) and input_type ( as seen inside the JSON above)

**Comment by congpine** [comment] 2015-11-17 13:12
ah I just found a link that mentioned document_type will allow more options, rather than using type (log and stdin only). 
Do you think it is the best way to identify the logs instead of adding more fields?
How about "input_type" ? even when I delete type, only use document_type, filebeat still send "input_type": ""

**Comment by ruflin** [comment] 2015-11-17 13:15
@congpine Will reply in more detail later as I have to test something in the above. About the type: We renamed type to input_type as type was confusing. So type in the config file does not exist anymore, only input_type and document_type. Document_type is the type of your document which will be stored in elasticsearch. Using fields as you did is the right way to go. But I have to check your config and why input_type is actually empty above ... Will do that later.

**Comment by ruflin** [comment] 2015-11-17 15:09
@congpine The empty input_type was a bug and is fixed here: https://github.com/elastic/filebeat/pull/247 Now looking at the logstash config.

**Comment by ruflin** [comment] 2015-11-17 15:34
@congpine briefly checked your config above. I think you need to use the following:

```
if [fields][logs_type] == "apache" {
...
```

Then it should work as expected. See also here: https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html

**Comment by congpine** [comment] 2015-11-17 15:47
thanks, @ruflin . 
that's the link I was looking for. I confirmed that the nested fields work correctly.
Do you have any docs that explain clearly how document_type and input_type would be used in practices? I can't get my head around these 2 parameters

**Comment by ruflin** [comment] 2015-11-17 16:17
@congpine Documentation can be found here:
* https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_document_type
* https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_input_type_2

Let me know if this helps. Important to understand is that input_type is a configuration for the filebeat harvester, to know from which input type to read (currently only file or stdin), document_type is a configuration for elasticsarch and defines in which elasticsearch type the events are stored.

**Comment by congpine** [comment] 2015-11-17 16:35
yes, I get that bits. We use ELK so I would have used document_type in filebeat.yml , get logstash-indexer match that logs and sending to ElasticSearch.
however, your comment above recommends to create new Fields in filebeat.yml and use it to match and indexing to ES.
So i'm not sure what the real benefit and different here. 
(Apology if my ES knowledge is limited)

**Comment by ruflin** [comment] 2015-11-17 16:44
@congpine The fields array can be used like tags. I think your use case is already a very good example. You could use here also document_type but in case you want multiple fields like this can't be handled with document_type: 
* logs_type: apache
* os: windows

These additional fields will help you for example to filter for all log entries from apache on windows machine.

**Comment by congpine** [comment] 2015-11-17 16:48
ah yes. That makes sense now.
Thanks for your help.

**Comment by ruflin** [comment] 2015-11-17 16:49
@congpine Looks like I have to extend the docs :-)

**Comment by ruflin** [comment] 2016-01-06 13:57
Closing as I think the issue was resolved.

**Closed by ruflin** 2016-01-06 13:57 UTC

**Comment by sunilmchaudhari** [comment] 2016-04-21 12:40
Hi,
I wwas using LSF before with new fields added in LSF.conf as below
{
      "paths": [ 
        "C:/logs/piletti/user-mgmt.log"
      ],
      "fields": { "type": "iam-logs","Application":"iam" }
    }

on Kibana I could see exactly same fields on left side filed list. 
However that is not the case with FB. 
1) It shows fields.application
2) Also it doesnt accept upper case in field value.

How to resolve this?
