### ISSUE TITLE
Filebeat mistakes remove and create of log file as a rename

### ISSUE THREAD

**Issue by MortenGuldager** [elastic/filebeat#271] opened 2015-11-20 11:51 UTC
`filebeat version 1.0.0-rc2 (amd64)` seems to get confused when logfiles being removed and new ones created. I suspect filebeat uses the inode number to tell if the log file has just been renamed. Unfortunately it is quite common that filesystems (linux ext4 and xfs at least) assign same inode number to newly created files if inode have been freed by a unlink moments earlier.

To reproduce:
* delete .filebeat and logs in spool/ 
* start filebeat with filebeat -c filebeat.yml -e -v -d "*"
* create a logfile with `date > spool/foo.log`
* inspect foo.log with stat

```
[mogul@oss-log01 spool]$ stat foo.log 
  File: ‘foo.log’
  Size: 29        	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 35696591    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1001/   mogul)   Gid: ( 1001/   mogul)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2015-11-20 12:25:52.663618287 +0100
Modify: 2015-11-20 12:25:52.664618284 +0100
Change: 2015-11-20 12:25:52.664618284 +0100
 Birth: -
```
* wait for filebeat to process the line
* stop filebeat or wait a minute for filebeat to close the log file
* remove foo.log 
* create bar.log
* inspect bar.log
```
[mogul@oss-log01 spool]$ stat bar.log 
  File: ‘bar.log’
  Size: 29        	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 35696591    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1001/   mogul)   Gid: ( 1001/   mogul)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2015-11-20 12:26:28.859491710 +0100
Modify: 2015-11-20 12:26:28.859491710 +0100
Change: 2015-11-20 12:26:28.859491710 +0100
 Birth: -
```
* observe that the inodes of foo.log and bar.log are the same
* start filebeat again
* filebeat detects this as a rename and therefore doesn't process the new content in bar.log

Short log snippet
```
2015/11/20 11:26:40.102123 prospector.go:218: DBG  Check file for harvesting: spool/bar.log
2015/11/20 11:26:40.102134 prospector.go:272: DBG  Start harvesting unknown file: spool/bar.log
2015/11/20 11:26:40.102144 registrar.go:204: INFO Old file with new name found: spool/foo.log is no spool/bar.log
2015/11/20 11:26:40.102149 registrar.go:173: INFO Detected rename of a previously harvested file: spool/foo.log -> spool/bar.log
2015/11/20 11:26:40.102155 prospector.go:316: DBG  Resuming harvester on a previously harvested file: spool/bar.log
2015/11/20 11:26:40.102189 log.go:62: INFO Harvester started for file: spool/bar.log
```

my config
```
filebeat:
  prospectors:
    - paths: [ "spool/*.log" ]
      ignore_older: 1m
      fields:
        foo: bar

output:
  console:
    pretty: true
```

**Comment by ruflin** [comment] 2015-11-20 12:06
@MortenGuldager Thanks a lot for reporting this. We indeed rely on inode + device to uniquely identify a file: https://github.com/elastic/filebeat/blob/master/input/file_other.go#L23 Are you aware of any other method to uniquely identify a file in case it was moved?

**Comment by ruflin** [comment] 2015-11-20 12:13
I did a brief test on ubuntu and can indeed reproduce this reliably with the following shell script:
```
touch test.log
stat test.log
rm test.log
touch test2.log
stat test2.log
```

The output is:
```
# sh test.sh 
  File: 'test.log'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 20h/32d	Inode: 2011        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-11-20 12:12:35.578340403 +0000
Modify: 2015-11-20 12:12:35.578340403 +0000
Change: 2015-11-20 12:12:35.578340403 +0000
 Birth: -
  File: 'test2.log'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 20h/32d	Inode: 2011        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-11-20 12:12:35.578340403 +0000
Modify: 2015-11-20 12:12:35.578340403 +0000
Change: 2015-11-20 12:12:35.578340403 +0000
 Birth: -
```

**Comment by bangert** [comment] 2015-11-20 12:29
Using fsnotify would presumably help, but would still miss renames, while filebeat isnt running.

Given that it is difficult (if not impossible) to get rename detection to work correctly, perhaps it should be configurable and even off by default.

**Comment by ruflin** [comment] 2015-11-20 12:35
@bangert The reason we have it enable by default the initial idea was to support log rotation. This means it is very common to have files renamed that should not be read anymore. Making it configurable would mean, either the detection is just name based, or it is based on inode/device. We will always need an option to continue existing files, so the fallback would be file path. This would cover all cases expect where the file is removed and a new one is created with the same name. And the third option could be do completely turn off storing the state of files.

As a note: Here is an issue already for fsnotify: https://github.com/elastic/filebeat/issues/17

**Comment by bangert** [comment] 2015-11-20 13:10
filebeat could write a uuid to a files extended attribute and use this to track the file.
even better filebeat could store how far it came in the file in extended attributes.
This would require write access to the files though.

another possiblity is to create hardlinks to all files watched. that way files cant just disappear. but that requires a scratch space on all disks that contain watched files (in addition to elevated rights to all files).

**Comment by ruflin** [comment] 2015-11-20 13:53
I like the idea with the uuid and attributes from a technical perspective as it would probably even make the .filebeat obsolete, but I worry a lot about writing to the files even though it is only attributes. I assume this would also lead to lots of access rights problems and not sure if everyone wants filebeat to write to all their files. 

Second has the challenges you mentioned. One idea that @urso brought up is, that we could check a predefined line/offset in the file, get the md5 of it and compare it later again to see if it is identical. With log files and timestamps this could work quite reliably.

**Comment by bangert** [comment] 2015-11-25 12:51
The md5 sum of a part of a file is a clever idea. It just isn't enough to make it correct, unfortunately. The more i think of it, the more convinced i am that a way to turn of rename detection is a necessity.

**Comment by bangert** [comment] 2015-11-26 13:23
rsyslog has a fileinput module:
http://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html
https://github.com/rsyslog/rsyslog/blob/master/plugins/imfile/imfile.c

**Comment by lwhitworth** [comment] 2016-02-12 13:19
Think I'm seeing the same issue on a RHEL 6.7 system:

```
2016-02-12T13:06:20Z INFO Old file with new name found: /data/logstash/resnet_argus.2016.02.10.21.01.01.0.txt is no /data/logstash/janet_argus.2016.02.12.12.02.37.0.txt
2016-02-12T13:06:20Z INFO Detected rename of a previously harvested file: /data/logstash/resnet_argus.2016.02.10.21.01.01.0.txt -> /data/logstash/janet_argus.2016.02.12.12.02.37.0.txt
2016-02-12T13:06:20Z INFO Harvester started for file: /data/logstash/janet_argus.2016.02.12.12.02.37.0.txt
```
As you can probably tell from the file names, .../janet_argus... is most definitely not a rename of .../resnet_argus...

Does anyone have any effective workarounds I can try?

**Comment by ruflin** [comment] 2016-02-16 17:27
@lwhitworth How does your log rotation / deletion look like at the moment?

**Comment by lwhitworth** [comment] 2016-02-18 08:44
Logs are deleted by a script which runs at 3am every morning and searches for files older than 24 hours and deletes them:

find /data/logstash/ -name "*.txt" -type f -mmin +$((60*24)) -exec rm {} \;

**Comment by ruflin** [comment] 2016-02-18 15:53
Further discussion going on here: https://discuss.elastic.co/t/old-file-with-new-name-found/41766

**Comment by morganchristiansson** [comment] 2016-04-22 11:24
Does filebeat recommend/support/not support any specific rotating policies? Would be good to know as I'm in the process of implementing this and most of them rely on renames which apparently can be problematic.

**Comment by ruflin** [comment] 2016-04-25 07:16
There is currently no document that describes which are recommended and which not. But I think based on your description you understood the limitations very well. 

Currently there is no option to disable the inode detection. We are currently discussing a fingerprint detection which does not rely on inode or filename together with LS. Some more details can be found here: https://github.com/jordansissel/ruby-filewatch/pull/79

**Comment by morganchristiansson** [comment] 2016-04-25 15:30
Yes. I've decided to go ahead with a renameless  approach where the app logs into the correct timedatestamped logfile. Exactly like in logs go into the correct datestamped logstash index in elasticsearch without renaming the indexes.

This seems like the superior approach to me.

Thank you.

**Comment by ruflin** [comment] 2016-04-26 06:37
@morganchristiansson Good to hear. You should not hit any issues with that. I hope we can offer more methods on how to track files in the future.

**Comment by morganchristiansson** [comment] 2016-04-27 15:38
Seems like I could still get issues in case an old log is deleted and a new one created with same inode? Which is why I asked how to disable the feature.

**Comment by ruflin** [comment] 2016-04-28 13:01
@morganchristiansson Correct. I'm currently working on improving that. As a first step I want that after the state file is cleaned up after `ignore_older`, so if a file reaches ignore_older it is removed from the state. So these inodes will be available again. Making sure you only remove files older then that, will "solve" your issue. But this is still under development ...

**Comment by ruflin** [comment] 2016-09-16 14:17
The new close_* and clean_* options in filebeat 5.0 should solve this issues. For more discussions also see https://github.com/elastic/beats/issues/1600 Closing this issue.

**Closed by ruflin** 2016-09-16 14:17 UTC
Labels: bug, discuss
