### ISSUE TITLE
 cannot use encoding.Replacement.NewEncoder

### ISSUE THREAD

**Issue by gohelion** [elastic/filebeat#340] opened 2016-03-01 06:20 UTC
Just pulled filebeat from my windows dev box and getting this error(same happens on mac too)

```
$ go get github.com/elastic/filebeat
# github.com/elastic/filebeat/harvester/encoding
src\github.com\elastic\filebeat\harvester\encoding\encoding.go:50: cannot use encoding.Replacement.NewEncoder (type func() *encoding.Encoder) as type func() transform.Transformer in field value
src\github.com\elastic\filebeat\harvester\encoding\encoding.go:51: cannot use encoding.Replacement.NewEncoder (type func() *encoding.Encoder) as type func() transform.Transformer in field value
````

Is this a known issue ?
Upon investigation, I was able to resolve this by the following changes:

```
#File: harvester\encoding\encoding.go
...
var utf8Encoding = enc(mixedEncoding{
        decoder: encoding.Replacement.NewDecoder,
        encoder: encoding.Replacement.NewEncoder,
})
...

#File: harvester\encoding\mixed.go
package encoding

import "golang.org/x/text/encoding"

type mixedEncoding struct {
        decoder func() *encoding.Decoder
        encoder func() *encoding.Encoder
}

func (m mixedEncoding) NewDecoder() *encoding.Decoder {
        return m.decoder()
}

func (m mixedEncoding) NewEncoder() *encoding.Encoder {
        return m.encoder()
}
```

**Comment by ruflin** [comment] 2016-03-01 08:02
We use a specific version of golang.org/x/text: https://github.com/elastic/beats/blob/master/glide.yaml#L30 This version is not compatible with the most recent version. Could it be that you don't have `GO15VENDOREXPERIMENT=1` enabled and it uses your the dependencies inside your GOPATH instead of the ones under vendor?

Side note: I updated your issue above with code formatting to make it better readable.

**Comment by ruflin** [comment] 2016-03-15 13:44
Closing this issue as I think it is not a bug. Please reopen if you think differently.

**Closed by ruflin** 2016-03-15 13:44 UTC

**Comment by lostz** [comment] 2016-03-28 08:13
It looks ugly. Can we have a better way to solve  it ?

**Comment by ruflin** [comment] 2016-03-28 08:50
@lostz Can you be more specific?

**Comment by lostz** [comment] 2016-03-28 09:00
I use part of code in my project , I still use golang.org/x/text/encoding , so......

**Comment by ruflin** [comment] 2016-03-28 09:08
You mean the version of text/encoding you use in your project conflicts with the version in the vendor directory from libbeat? If this is the case, one solution that could probably work but I didn't test is to have a local vendor directory which has text/encoding inside with the specific version tagged. Agree a little bit ugly, but could work.

The best way forward here is to update the text/encoding version we use in libbeat. We have that on our Todo list but there are currently other things with higher priority. So we would be more then happy if you could pick this up and open a PR with a more recent version.

Third solution is that you use in your code also the older version of text/encoding.

**Comment by lostz** [comment] 2016-03-28 09:18
ok,thanks.
