### ISSUE TITLE
Filebeat do not track file rotation

### ISSUE THREAD

**Issue by smaniero** [elastic/filebeat#334] opened 2016-02-14 00:40 UTC
I'm confused by the behavior of filebeat when detect file rotation.

To reproduce:

my config file:
```
filebeat:
  prospectors:
    -
      paths:
        - "/var/log/test/*.log"

output:
  console:
    pretty: true
```

Create log file with command:
```
echo START > test.log
```

registry file contains:
```
{"/var/log/test/test.log":{"source":"/var/log/test/test.log","offset":6,"FileStateOS":{"inode":4956173,"device":2065}}}
```

Rotate log file with command:
```
mv /var/log/test/test.log /var/log/test/rotated.log
echo START > test.log
```

Now I except 2 file in registy file, instead:
```
{"/var/log/test/test.log":{"source":"/var/log/test/test.log","offset":6,"FileStateOS":{"inode":4956173,"device":2065}}}
```

So I try to modify rotated.log file with command:
```
echo APPEND > /var/log/test/rotated.log
```
 
and out stdout I see:
```
{
  "@timestamp": "2016-02-14T00:22:07.921Z",
  "beat": {
    "hostname": "logs.sfera.net",
    "name": "logs.sfera.net"
  },
  "count": 1,
  "fields": null,
  "input_type": "log",
  "message": "APPEND",
  "offset": 6,
  "source": "/var/log/test/test.log",
  "type": "log"
}
```

Why filebeat detect rename but non modify the references into the registry and configure harvester correctly?

**Comment by ruflin** [comment] 2016-03-15 14:02
Is this a duplicate of https://github.com/elastic/beats/issues/1010 ? Please reopen if not.

**Closed by ruflin** 2016-03-15 14:02 UTC
