### ISSUE TITLE
On demand only

### ISSUE THREAD

**Issue by urso** [elastic/filebeat#219] opened 2015-11-10 11:36 UTC
Start filebeat on demand only to forward a given set of files as is (registrar required?). Do not tail files to be send.
Stop filebeat once done.

Example use-case (replay without re-running any processing generating the events):
- Have logstash file output plugin write all events to file logging all events being indexed
- replay by sending written log files (with json) via filebeat to logstash

**Comment by ruflin** [comment] 2015-11-10 21:39
An extended use case here could be, that every time files change, the full file is sent again. This can be interesting for more binary files. In this case a registrar would still be needed.

**Comment by ruflin** [comment] 2016-03-15 13:57
Closing as duplicate of https://github.com/elastic/filebeat/issues/134

**Closed by ruflin** 2016-03-15 13:57 UTC
